# Utilizamos la imagen oficial de Node.js en su versión alpine (ligera)
FROM node:alpine

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos el script
COPY script.js .

# Ejecutamos el script
CMD ["node", "script.js"]